on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

name: macOS Build

jobs:
  build:
    name: Build
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          architecture: x64
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          miniconda-version: latest
      - name: Build macOS wheels
        shell: bash -l {0}
        run: |
            export MACOSX_DEPLOYMENT_TARGET=10.9
            curl -sqL https://github.com/joseluisq/macosx-sdks/releases/download/14.0/MacOSX14.0.sdk.tar.xz | tar -xC $HOME
            # set minimum sdk version to our target
            plutil -replace MinimumSDKVersion -string ${MACOSX_DEPLOYMENT_TARGET} $(xcode-select -p)/Platforms/MacOSX.platform/Info.plist
            plutil -replace DTSDKName -string macosx${MACOSX_DEPLOYMENT_TARGET}internal $(xcode-select -p)/Platforms/MacOSX.platform/Info.plist
            conda create -qy -n fasttext_venv python=${{ matrix.python-version }} wheel
            conda init bash
            source ~/.bash_profile
            conda activate fasttext_venv
            python -c "import sys; print(sys.version)"
            export CFLAGS="${CFLAGS} -isysroot $HOME/MacOSX14.0.sdk"
            export CXXFLAGS="${CXXFLAGS} -isysroot $HOME/MacOSX14.0.sdk"
            python setup.py bdist_wheel
            pip install delocate
            delocate-wheel -w dist -v dist/fasttext*.whl
            ls -lrth dist/
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: macos-wheels
          path: dist/fasttext_numpy2_wheel-*.whl
      - name: Publish macOS package
        if: github.event_name == 'workflow_dispatch' || startsWith(github.event.ref, 'refs/tags')
        shell: bash -l {0}
        run: |
            conda activate fasttext_venv
            pip install twine
            TWINE_USERNAME=__token__ TWINE_PASSWORD=${{ secrets.pypi_password }} twine upload --skip-existing dist/*
